[package]
name = "adventofcode19"
version = "0.1.0"
authors = ["Catlinman <contact@catlinman.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "1a"
path = "src/1/1a.rs"

[[bin]]
name = "1b"
path = "src/1/1b.rs"
